
export const GENRELIST = {
    GENRE_DATA_REQUEST: 'GENRE_DATA_REQUEST',
    GENRE_DATA_SUCCESS: 'GENRE_DATA_SUCCESS',
    GENRE_DATA_FAILED: 'GENRE_DATA_FAILURE',
}
export const LOGIN = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_REQUEST_FAIL: 'LOGIN_REQUEST_FAIL'
}
export const CREATE_PLAYLIST = {
    REQUEST: 'CREATE_PLAYLIST_REQUEST',
    SUCCESS: 'CREATE_PLAYLIST_SUCCESS',
    FAIL: 'CREATE_PLAYLIST_FAIL'
}
export const COMMONALERT = {
    REQUEST: "COMMONALERT_REQUEST",
    SUCCESS: "COMMONALERT_SUCCESS",
    FAIL: "COMMONALERT_FAIL",
}
export const SLOGIN = {
    SLOGIN_REQUEST: 'SLOGIN_REQUEST',
    SLOGIN_SUCCESS: 'SLOGIN_SUCCESS',
    SLOGIN_REQUEST_FAIL: 'SLOGIN_REQUEST_FAIL'
}
export const CHECK_USER= {
    CHECK_USER_REQUEST: "CHECK_USER_REQUEST",
    CHECK_USER_SUCCESS:'CHECK_USER_SUCCESS',
    CHECK_USER_FAIL: 'CHECK_USER_FAIL',
}
export const SIGNUP = {
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_REQUEST_FAIL: 'SIGNUP_REQUEST_FAIL'
}
export const EDIT_ACCOUNT = {
    EDIT_ACCOUNT_REQUEST: 'EDIT_ACCOUNT_REQUEST',
    EDIT_ACCOUNT_SUCCESS: 'EDIT_ACCOUNT_SUCCESS',
    EDIT_ACCOUNT_FAIL: 'EDIT_ACCOUNT_FAIL'
}
export const FORGOT_PASSWORD = {
    FORGOT_PASSWORD_REQUEST:'FORGOT_PASSWORD_REQUEST',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAIL:'FORGOT_PASSWORD_FAIL',
}
export const RENDERGENRE = {
    GENRE_LIST_REQUEST: 'GENRE_LIST_REQUEST',
    GENRE_LIST_SUCCESS: 'GENRE_LIST_SUCCESS',
    GENRE_LIST_FAILED: 'GENRE_LIST_FAILED',
}
export const RENDERGENRETYPE = {
    GENRE_TYPE_REQUEST: 'GENRE_TYPE_REQUEST',
    GENRE_TYPE_SUCCESS: 'GENRE_TYPE_SUCCESS',
    GENRE_TYPE_FAILED: 'GENRE_TYPE_FAILED',
}
export const SET_GENRE={
    SET_GENRE: 'SET_GENRE',
}
export const SET_TYPE={
    SET_TYPE: 'SET_TYPE',
}
export const SET_PRIVACY={
    SET_PRIVACY: 'SET_PRIVACY',
}
export const PUBLISH_POST = {
    PUBLISH_POST_REQUEST: 'PUBLISH_POST_REQUEST',
    PUBLISH_POST_SUCCESS: 'PUBLISH_POST_SUCCESS',
    PUBLISH_POST_FAILED: 'PUBLISH_POST_FAILED',
}
export const EDIT_POST = {
    EDIT_POST_REQUEST: 'EDIT_POST_REQUEST',
    EDIT_POST_SUCCESS: 'EDIT_POST_SUCCESS',
    EDIT_POST_FAILED: 'EDIT_POST_FAILED',
}
export const GETSUBLEVEL ={
    GETSUBLEVEL_REQUEST: 'GETSUBLEVEL_REQUEST',
    GETSUBLEVEL_SUCCESS: 'GETSUBLEVEL_SUCCESS',
    GETSUBLEVEL_FAILED: 'GETSUBLEVEL_FAILED',
}
export const SET_LEVEL={
    SET_LEVEL: 'SET_LEVEL',
}
export const SET_AGE={
    SET_AGE: 'SET_AGE',
}
export const SET_GENDER={
    SET_GENDER: 'SET_GENDER',
}
export const SET_SUB={
    SET_SUB: 'SET_SUB',
}

export const SELECT={
    SELECTREQUEST: 'SELECTREQUEST',
    SELECTSUCCESS:"SELECTSUCCESS",
    SELECTFAILURE:"SELECTFAILURE"
}
export const SELECTEMAIL={
    SELECTREQUESTEMAIL: 'SELECTREQUESTEMAIL',
    SELECTSUCCESSEMAIL:"SELECTSUCCESSEMAIL",
    SELECTFAILUREEMAIL:"SELECTFAILUREEMAIL"
}
export const STOREIMAGE={
    STOREIMAGE :"STOREIMAGE"
}
export const SET_USERNAME={
    SET_USERNAME: 'SET_USERNAME',
}



export const FETCHPLAYLIST = {
    REQUEST: 'FETCHPLAYLIST_REQUEST',
    SUCCESS: 'FETCHPLAYLIST_SUCCESS',
    FAIL: 'FETCHPLAYLIST_FAIL'
}

export const FETCHDISCOVERLIST = {
    REQUEST: 'FETCHDISCOVERLIST_REQUEST',
    SUCCESS: 'FETCHDISCOVERLIST_SUCCESS',
    FAIL: 'FETCHDISCOVERLIST_FAIL'
}


export const FETCHSUGGESTIONS = {
    REQUEST: 'FETCHSUGGESTIONS_REQUEST',
    SUCCESS: 'FETCHSUGGESTIONS_SUCCESS',
    FAIL: 'FETCHSUGGESTIONS_FAIL'
}


export const FETCHDATALIST = {
    REQUEST: 'FETCHDATALIST_REQUEST',
    SUCCESS: 'FETCHDATALIST_SUCCESS',
    FAIL: 'FETCHDATALIST_FAIL'
}
export const ARTIST_LIST={
    REQUEST: 'ARTIST_LIST_REQUEST',
    SUCCESS : "ARTIST_LIST_SUCCESS",
    FAIL : "ARTIST_LIST_FAIL"
}

//ARTIST_FOLLOW
export const ARTIST_FOLLOW={
    REQUEST: 'ARTIST_FOLLOW_REQUEST',
    SUCCESS : "ARTIST_FOLLOW_SUCCESS",
    FAIL : "ARTIST_FOLLOW_FAIL"
}

//USER_FEED
export const USER_FEED={
    REQUEST: 'USER_FEED_REQUEST',
    SUCCESS : "USER_FEED_SUCCESS",
    FAIL : "USER_FEED_FAIL"
}

// USER_STORY
export const USER_STORY={
    REQUEST: 'USER_STORY_REQUEST',
    SUCCESS : "USER_STORY_SUCCESS",
    FAIL : "USER_STORY_FAIL"
}

//SWITCH_PROFILE
export const SWITCH_PROFILE={
    REQUEST: 'SWITCH_PROFILE_REQUEST',
    SUCCESS : "SWITCH_PROFILE_SUCCESS",
    FAIL : "SWITCH_PROFILE_FAIL"
}